sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t foreverithd/react-devops -f Dockerfile.dev .

script:
  - docker run -e CI=true foreverithd/react-devops npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-devops-bnstk"
  env: "Reactdevopsbnstk-env"
  bucket_name: "elasticbeanstalk-us-east-2-824192598227"
  bucket_path: "react-devops-bnstk"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"